name: Code quality and testing analysis with flake8 and unittest
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-flake8-and-unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./plugin

    steps:

      - name: checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install uv 
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.33"
          enable-cache: true
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Run Ruff linter check
        run: uvx ruff check components/

      - name: Run Ruff formatter check
        run: uvx ruff format --check components/
      
      - name: Run tests
        run: uv run python -m unittest discover tests/

  
# references: 
# https://pydevtools.com/handbook/tutorial/setting-up-github-actions-with-uv/
# https://docs.astral.sh/uv/guides/integration/github/#setting-up-python